### ISSUE TITLE
calendar does not seem to change date

### ISSUE THREAD

**Issue by khumnath** [khumnath/nepdate#11]
i updated code in 2081 asar month but date stucked there. no time to see now. will update later

**Comment by nepvibes** [comment]
@khumnath calendar is updating correctly. where is not changing?

**Comment by khumnath** [comment]
oh i have not mentioned that calendar on javascript based page is not updating.

**Comment by khumnath** [comment]
@nepvibes  I am not  good at javascript.  convertor is working fine. hidden calendar section with css and closing this issue now.

**Comment by nepvibes** [comment]
Got it 🤟👍
